#!/bin/bash
# Automatically create required HSM tokens based on inventory configuration
# Supports multi-token mode where each org uses an independent token

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INVENTORY_FILE="$PROJECT_ROOT/ansible/inventory/fabric-x.yaml"

# Default config (can be read from inventory or env vars)
CONFIG_PATH="${SOFTHSM2_CONF:-/tmp/softhsm2.conf}"
PIN="${HSM_PIN:-1234}"
SOPIN="${HSM_SOPIN:-5678}"

# Set environment variables
export SOFTHSM2_CONF="$CONFIG_PATH"

# Create config directory
CONFIG_DIR=$(dirname "$CONFIG_PATH")
mkdir -p "$CONFIG_DIR"

# Create token directory
TOKEN_DIR="${SOFTHSM_TOKEN_DIR:-$HOME/softhsm/tokens}"
mkdir -p "$TOKEN_DIR"

# Generate SoftHSM2 config file
cat > "$CONFIG_PATH" <<EOF
# SoftHSM2 configuration file
# Generated by setup-hsm-tokens.sh

directories.tokendir = $TOKEN_DIR
objectstore.backend = file

# Logging
log.level = INFO
EOF

echo "SoftHSM2 configuration created at: $CONFIG_PATH"
echo "Token directory: $TOKEN_DIR"

# Extract tokens to create from the inventory file
# Look for all hsm_config.token_label entries
TOKENS=()

if [ -f "$INVENTORY_FILE" ]; then
    # Extract all token_label values (supports multi-token mode)
    # Note: inventory may include template variables, so only use concrete values
    while IFS= read -r line; do
        # Match token_label: "..." pattern
        if [[ $line =~ token_label:[[:space:]]*\"([^\"]+)\" ]]; then
            token="${BASH_REMATCH[1]}"
            # Skip lines with template variables (e.g., {{ orderer_group }})
            if [[ ! "$token" =~ \{\{.*\}\} ]]; then
                if [[ ! " ${TOKENS[@]} " =~ " ${token} " ]]; then
                    TOKENS+=("$token")
                fi
            fi
        fi
    done < <(grep -i "token_label" "$INVENTORY_FILE" || true)
    
    # If tokens contain template variables or none were found, fallback to defaults
    # Expand based on common orderer organization patterns
    if [ ${#TOKENS[@]} -eq 0 ] || [[ "${TOKENS[*]}" =~ \{\{ ]]; then
        echo "Note: Using default tokens based on common orderer organization pattern" >&2
        TOKENS=(
            "FabricToken-Ordererorg1"
            "FabricToken-Ordererorg2"
            "FabricToken-Ordererorg3"
            "FabricToken-Ordererorg4"
        )
    fi
else
    echo "Warning: Inventory file not found at $INVENTORY_FILE, using default tokens" >&2
    TOKENS=(
        "FabricToken-Ordererorg1"
        "FabricToken-Ordererorg2"
        "FabricToken-Ordererorg3"
        "FabricToken-Ordererorg4"
    )
fi

echo "Tokens to create: ${TOKENS[*]}"

# Check if softhsm2-util is available
if ! command -v softhsm2-util &> /dev/null; then
    echo "ERROR: softhsm2-util not found. Please install SoftHSM2." >&2
    echo "  macOS: brew install softhsm" >&2
    echo "  Linux: apt-get install softhsm2" >&2
    exit 1
fi

# Function to find an available slot
find_available_slot() {
    # Get all slot info
    local slots_output=$(softhsm2-util --show-slots 2>/dev/null || echo "")
    
    # Find an uninitialized slot (Token present: yes but Initialized: no)
    # Simple approach: scan all slots and pick the first uninitialized one
    local available_slot=""
    
    # Parse slot output to find an uninitialized slot
    local current_slot=""
    while IFS= read -r line; do
        if [[ $line =~ ^Slot[[:space:]]+([0-9]+)$ ]]; then
            current_slot="${BASH_REMATCH[1]}"
        elif [[ -n "$current_slot" ]] && [[ $line =~ Initialized:[[:space:]]*no ]]; then
            available_slot="$current_slot"
            break
        fi
    done <<< "$slots_output"
    
    # If no uninitialized slot is found, fallback to slot 0 (SoftHSM auto-assigns)
    echo "${available_slot:-0}"
}

# Create or verify each token
for token in "${TOKENS[@]}"; do
    echo ""
    echo "Processing token: $token"
    
    # Check if the token already exists
    if softhsm2-util --show-slots 2>/dev/null | grep -q "Label.*$token"; then
        echo "  Token '$token' already exists, skipping..."
    else
        echo "  Creating token '$token'..."
        # Find an available slot
        available_slot=$(find_available_slot)
        echo "  Using slot: $available_slot"
        
        # Create the token in the available slot
        if softhsm2-util --init-token \
            --slot "$available_slot" \
            --label "$token" \
            --pin "$PIN" \
            --so-pin "$SOPIN" 2>&1; then
            echo "  Token '$token' created successfully"
        else
            echo "  Warning: Failed to create token '$token'" >&2
        fi
    fi
done

echo ""
echo "=== Current HSM Tokens ==="
softhsm2-util --show-slots

echo ""
echo "HSM setup completed!"
echo "Configuration: $CONFIG_PATH"
echo "Token directory: $TOKEN_DIR"

