/*
Copyright IBM Corp. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
package genesis

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/ethsign/fabric-x-network/tools/config-builder/internal/config"
)

// Generator handles genesis block generation
type Generator struct {
	config       *config.NetworkConfig
	outputDir    string
	verbose      bool
	configtxgen  string // path to configtxgen binary (empty if using container)
	useContainer bool   // whether to use Docker container instead of local binary
}

// NewGenerator creates a new genesis block generator
func NewGenerator(cfg *config.NetworkConfig, outputDir string, verbose bool) *Generator {
	return &Generator{
		config:    cfg,
		outputDir: outputDir,
		verbose:   verbose,
	}
}

// Generate generates the genesis block
func (g *Generator) Generate() error {
	// Step 1: Create placeholder shared_config.binpb if it doesn't exist
	// TODO: This should be generated by armageddon tool in the future
	if err := g.createPlaceholderSharedConfig(); err != nil {
		g.log("Warning: failed to create placeholder shared_config.binpb: %v", err)
	}

	// Step 2: Generate configtx.yaml
	configPath, err := g.generateConfigtx()
	if err != nil {
		return fmt.Errorf("failed to generate configtx.yaml: %w", err)
	}

	// Step 3: Try to find configtxgen (prefer Docker container, fallback to local binary)
	if err := g.findConfigtxgen(); err != nil {
		// If configtxgen is not available, just generate configtx.yaml
		g.log("configtxgen not found, only configtx.yaml was generated")
		g.log("  To generate genesis block, please install configtxgen or build it from source")
		return nil
	}

	// Step 4: Run configtxgen
	if err := g.runConfigtxgen(configPath); err != nil {
		return fmt.Errorf("failed to run configtxgen: %w", err)
	}

	return nil
}

// createPlaceholderSharedConfig is no longer needed as armageddon is integrated
// This function is kept for backward compatibility but does nothing
func (g *Generator) createPlaceholderSharedConfig() error {
	// Armageddon integration is now complete, no placeholder needed
	return nil
}

// GenerateConfigtxOnly generates only the configtx.yaml file
func (g *Generator) GenerateConfigtxOnly() (string, error) {
	return g.generateConfigtx()
}

// findConfigtxgen locates configtxgen, preferring Docker container (matching Ansible behavior)
// Falls back to local binary if container is not available
func (g *Generator) findConfigtxgen() error {
	// Priority 1: Try to use Docker container (matching Ansible's default behavior)
	if g.tryDockerConfigtxgen() {
		g.useContainer = true
		g.log("Using configtxgen from Docker container: %s", g.config.Docker.ToolsImage)
		return nil
	}

	// Priority 2: Use local binary (build if necessary)
	g.useContainer = false
	absOutputDir, err := filepath.Abs(g.outputDir)
	if err != nil {
		return fmt.Errorf("failed to get absolute output path: %w", err)
	}

	// Target location for built configtxgen
	cliDir := filepath.Join(absOutputDir, "cli")
	targetPath := filepath.Join(cliDir, "configtxgen")

	// Method 1: Check if already built
	if _, err := os.Stat(targetPath); err == nil {
		g.log("Found configtxgen at: %s", targetPath)
		g.configtxgen = targetPath
		return nil
	}

	// Method 2: Try to build from local source
	sourceDir := filepath.Join(g.config.ProjectDir, "tools", "configtxgen")
	if _, err := os.Stat(filepath.Join(sourceDir, "main.go")); err == nil {
		g.log("Building configtxgen from local source: %s", sourceDir)
		if err := g.buildConfigtxgen(sourceDir, targetPath); err != nil {
			g.log("Failed to build from local source: %v", err)
		} else {
			g.configtxgen = targetPath
			return nil
		}
	}

	// Method 3: Try to install using go install (like Ansible bin/install)
	g.log("Attempting to install configtxgen using go install...")
	if err := g.installConfigtxgen(targetPath); err != nil {
		g.log("Failed to install using go install: %v", err)
	} else {
		if _, err := os.Stat(targetPath); err == nil {
			g.configtxgen = targetPath
			return nil
		}
	}

	// Method 4: Try to find in PATH
	path, err := exec.LookPath("configtxgen")
	if err == nil {
		g.log("Found configtxgen in PATH: %s", path)
		g.configtxgen = path
		return nil
	}

	return fmt.Errorf("configtxgen not found. Tried: Docker container, local build, go install, PATH")
}

// tryDockerConfigtxgen checks if Docker and the tools image are available
func (g *Generator) tryDockerConfigtxgen() bool {
	// Check if docker command is available
	if _, err := exec.LookPath("docker"); err != nil {
		g.log("Docker not found in PATH, will use local binary")
		return false
	}

	// Check if the image exists or can be pulled
	image := g.config.Docker.ToolsImage
	if image == "" {
		image = "docker.io/hyperledger/fabric-x-tools:0.0.4" // Default from Ansible
	}

	// Try to inspect the image to see if it exists
	cmd := exec.Command("docker", "image", "inspect", image)
	cmd.Stdout = nil
	cmd.Stderr = nil
	if err := cmd.Run(); err == nil {
		return true // Image exists
	}

	// Image doesn't exist, but Docker is available
	// We'll try to use it anyway and let docker pull it if needed
	g.log("Docker image %s not found locally, will attempt to pull when needed", image)
	return true
}

// buildConfigtxgen builds the configtxgen binary from source
func (g *Generator) buildConfigtxgen(sourceDir, targetPath string) error {
	// Create output directory
	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Build command
	cmd := exec.Command("go", "build", "-o", targetPath, ".")
	cmd.Dir = sourceDir
	cmd.Env = os.Environ()

	g.log("Running: go build -o %s .", targetPath)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("go build failed: %w\nOutput: %s", err, string(output))
	}

	g.log("Successfully built configtxgen at: %s", targetPath)
	return nil
}

// installConfigtxgen installs configtxgen using go install (like Ansible does)
// This matches Ansible's bin/install task which uses:
//
//	go install github.com/hyperledger/fabric-x/tools/configtxgen@v0.0.4
func (g *Generator) installConfigtxgen(targetPath string) error {
	// Create output directory
	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Use go install with GOBIN set to output directory
	// This matches Ansible's approach: GOBIN={{ bin_output_dir }} go install {{ bin_go_package }}
	packagePath := "github.com/hyperledger/fabric-x/tools/configtxgen@v0.0.4"

	cmd := exec.Command("go", "install", packagePath)
	cmd.Env = os.Environ()
	cmd.Env = append(cmd.Env, fmt.Sprintf("GOBIN=%s", filepath.Dir(targetPath)))

	g.log("Running: GOBIN=%s go install %s", filepath.Dir(targetPath), packagePath)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("go install failed: %w\nOutput: %s", err, string(output))
	}

	// Verify the binary was installed
	if _, err := os.Stat(targetPath); os.IsNotExist(err) {
		return fmt.Errorf("configtxgen was not installed to expected location: %s", targetPath)
	}

	g.log("Successfully installed configtxgen at: %s", targetPath)
	return nil
}

// generateConfigtx generates the configtx.yaml file using template
func (g *Generator) generateConfigtx() (string, error) {
	return g.generateConfigtxFromTemplate()
}

// getOrdererEndpoints returns orderer endpoints for an organization
func (g *Generator) getOrdererEndpoints(org *config.OrdererOrg) []string {
	var endpoints []string
	for _, orderer := range org.Orderers {
		host := orderer.Host
		if host == "" {
			host = "localhost"
		}
		port := orderer.Port
		if port == 0 {
			port = 7050
		}

		// Format: id=<group>,broadcast,<host>:<port> for router
		// Format: id=<group>,deliver,<host>:<port> for assembler
		if orderer.Type == "router" {
			endpoints = append(endpoints, fmt.Sprintf("id=1,broadcast,%s:%d", host, port))
		} else if orderer.Type == "assembler" {
			endpoints = append(endpoints, fmt.Sprintf("id=1,deliver,%s:%d", host, port))
		}
	}
	return endpoints
}

// runConfigtxgen executes the configtxgen tool (via Docker container or local binary)
func (g *Generator) runConfigtxgen(configPath string) error {
	absOutputDir, _ := filepath.Abs(g.outputDir)
	outputDir := filepath.Join(absOutputDir, "build", "config", "configtxgen-artifacts")
	genesisBlockPath := filepath.Join(outputDir, g.config.ChannelID+"_block.pb")

	if g.useContainer {
		return g.runConfigtxgenContainer(configPath, absOutputDir, genesisBlockPath)
	}

	return g.runConfigtxgenLocal(configPath, genesisBlockPath)
}

// runConfigtxgenContainer runs configtxgen using Docker container (matching Ansible behavior)
func (g *Generator) runConfigtxgenContainer(configPath, absOutputDir, genesisBlockPath string) error {
	image := g.config.Docker.ToolsImage
	if image == "" {
		image = "docker.io/hyperledger/fabric-x-tools:0.0.4" // Default from Ansible
	}

	// Docker paths (matching Ansible's configtxgen_docker_output_dir)
	dockerOutputDir := "/tmp/configtxgen-artifacts"
	dockerCryptogenDir := "/tmp/cryptogen-artifacts"
	dockerArmageddonDir := "/tmp/armageddon-artifacts"

	// Get absolute paths for mounting
	outputDir := filepath.Join(absOutputDir, "build", "config", "configtxgen-artifacts")
	cryptogenArtifactsDir := filepath.Join(absOutputDir, "build", "config", "cryptogen-artifacts")
	armageddonArtifactsDir := filepath.Join(absOutputDir, "build", "config", "armageddon-artifacts")

	// Ensure directories exist
	if err := os.MkdirAll(outputDir, 0750); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Build docker run command (matching Ansible's container/start.yaml)
	args := []string{
		"run",
		"--rm", // Auto-remove container (matches container_autoremove: true)
		"-v", fmt.Sprintf("%s:%s", outputDir, dockerOutputDir),
		"-v", fmt.Sprintf("%s:%s", cryptogenArtifactsDir, dockerCryptogenDir),
		"-v", fmt.Sprintf("%s:%s", armageddonArtifactsDir, dockerArmageddonDir),
	}

	// Set user to current user (matches container_run_as_host_user: true)
	if uid := os.Getuid(); uid != 0 {
		if gid := os.Getgid(); gid != 0 {
			args = append(args, "-u", fmt.Sprintf("%d:%d", uid, gid))
		}
	}

	// Copy configtx.yaml to outputDir and replace paths with container paths
	configFile := filepath.Base(configPath)
	configInOutputDir := filepath.Join(outputDir, configFile)
	configData, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("failed to read config file: %w", err)
	}

	// Replace host paths with container paths in configtx.yaml
	configStr := string(configData)
	// Replace cryptogen artifacts path
	configStr = strings.ReplaceAll(configStr, cryptogenArtifactsDir, dockerCryptogenDir)
	// Replace armageddon artifacts path
	configStr = strings.ReplaceAll(configStr, armageddonArtifactsDir, dockerArmageddonDir)

	if err := os.WriteFile(configInOutputDir, []byte(configStr), 0644); err != nil {
		return fmt.Errorf("failed to copy config file to container directory: %w", err)
	}

	// Container command (matching Ansible's container_command)
	containerCmd := fmt.Sprintf("configtxgen -channelID %s -profile OrgsChannel -configPath %s --outputBlock %s/%s_block.pb",
		g.config.ChannelID, dockerOutputDir, dockerOutputDir, g.config.ChannelID)
	args = append(args, image, "sh", "-c", containerCmd)

	g.log("Running configtxgen via Docker: docker %v", args)

	cmd := exec.Command("docker", args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("configtxgen container failed: %w\nOutput: %s", err, string(output))
	}

	if g.verbose {
		fmt.Println(string(output))
	}

	// Log the generated genesis block location with absolute path and size
	return g.logGenesisBlock(genesisBlockPath)
}

// runConfigtxgenLocal runs configtxgen using local binary
func (g *Generator) runConfigtxgenLocal(configPath, genesisBlockPath string) error {
	args := []string{
		"-channelID", g.config.ChannelID,
		"-profile", "OrgsChannel",
		"-configPath", filepath.Dir(configPath),
		"--outputBlock", genesisBlockPath,
	}

	cmd := exec.Command(g.configtxgen, args...)
	cmd.Dir = g.config.ProjectDir

	// Set FABRIC_CFG_PATH to the config directory
	cmd.Env = os.Environ()
	cmd.Env = append(cmd.Env, fmt.Sprintf("FABRIC_CFG_PATH=%s", filepath.Dir(configPath)))

	g.log("Running configtxgen: %s %v", g.configtxgen, args)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("configtxgen failed: %w\nOutput: %s", err, string(output))
	}

	if g.verbose {
		fmt.Println(string(output))
	}

	// Log the generated genesis block location with absolute path and size
	return g.logGenesisBlock(genesisBlockPath)
}

// logGenesisBlock logs information about the generated genesis block
func (g *Generator) logGenesisBlock(genesisBlockPath string) error {
	if absPath, err := filepath.Abs(genesisBlockPath); err == nil {
		if info, err := os.Stat(absPath); err == nil {
			fmt.Printf("Genesis block generated successfully!\n")
			fmt.Printf("  Location: %s\n", absPath)
			fmt.Printf("  Size: %s\n", formatBytes(info.Size()))
		} else {
			fmt.Printf("Genesis block generated successfully at: %s\n", absPath)
		}
	} else {
		fmt.Printf("Genesis block generated successfully at: %s\n", genesisBlockPath)
	}
	return nil
}

// log prints a message if verbose mode is enabled
func (g *Generator) log(format string, args ...interface{}) {
	if g.verbose {
		fmt.Printf("  [genesis] "+format+"\n", args...)
	}
}

// formatBytes formats bytes to human-readable format
func formatBytes(bytes int64) string {
	const unit = 1024
	if bytes < unit {
		return fmt.Sprintf("%d B", bytes)
	}
	div, exp := int64(unit), 0
	for n := bytes / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(bytes)/float64(div), "KMGTPE"[exp])
}
