/*
Copyright IBM Corp. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/
package hsm

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/ethsign/fabric-x-network/tools/config-builder/internal/config"
)

// SoftHSMProvider implements the Provider interface for SoftHSM2
type SoftHSMProvider struct {
	config      *config.HSMConfig
	utilPath    string // Path to softhsm2-util binary
	libraryPath string
}

// NewSoftHSMProvider creates a new SoftHSM2 provider
func NewSoftHSMProvider(cfg *config.HSMConfig) (*SoftHSMProvider, error) {
	provider := &SoftHSMProvider{
		config: cfg,
	}

	// Find softhsm2-util
	utilPath, err := findSoftHSMUtil()
	if err != nil {
		return nil, fmt.Errorf("softhsm2-util not found: %w", err)
	}
	provider.utilPath = utilPath

	// Determine library path
	libraryPath := cfg.LibraryPath
	if libraryPath == "" {
		libraryPath = autoDetectSoftHSMLibrary()
	}
	provider.libraryPath = libraryPath

	return provider, nil
}

// Name returns the provider name
func (p *SoftHSMProvider) Name() string {
	return "softhsm"
}

// Initialize sets up the SoftHSM2 environment
func (p *SoftHSMProvider) Initialize() error {
	// Create config directory
	configDir := filepath.Dir(p.config.ConfigPath)
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Create token directory
	if err := os.MkdirAll(p.config.TokenDir, 0755); err != nil {
		return fmt.Errorf("failed to create token directory: %w", err)
	}

	// Generate SoftHSM2 configuration file
	configContent := fmt.Sprintf(`# SoftHSM2 configuration file
# Generated by network-builder HSM provider

directories.tokendir = %s
objectstore.backend = file

# Logging
log.level = INFO
`, p.config.TokenDir)

	if err := os.WriteFile(p.config.ConfigPath, []byte(configContent), 0644); err != nil {
		return fmt.Errorf("failed to write SoftHSM2 config: %w", err)
	}

	return nil
}

// CreateToken creates a SoftHSM2 token
func (p *SoftHSMProvider) CreateToken(label string) error {
	// Check if token already exists
	exists, err := p.TokenExists(label)
	if err != nil {
		return fmt.Errorf("failed to check token existence: %w", err)
	}
	if exists {
		return nil // Token already exists
	}

	// Find available slot
	slot, err := p.findAvailableSlot()
	if err != nil {
		return fmt.Errorf("failed to find available slot: %w", err)
	}

	// Create token
	cmd := exec.Command(p.utilPath,
		"--init-token",
		"--slot", fmt.Sprintf("%d", slot),
		"--label", label,
		"--pin", p.config.PIN,
		"--so-pin", p.config.SOPIN,
	)
	cmd.Env = append(os.Environ(), fmt.Sprintf("SOFTHSM2_CONF=%s", p.config.ConfigPath))

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to create token '%s': %w\nOutput: %s", label, err, string(output))
	}

	return nil
}

// TokenExists checks if a token with the given label exists
func (p *SoftHSMProvider) TokenExists(label string) (bool, error) {
	cmd := exec.Command(p.utilPath, "--show-slots")
	cmd.Env = append(os.Environ(), fmt.Sprintf("SOFTHSM2_CONF=%s", p.config.ConfigPath))

	output, err := cmd.CombinedOutput()
	if err != nil {
		return false, fmt.Errorf("failed to list tokens: %w", err)
	}

	// Check if the label appears in the output
	outputStr := string(output)
	lines := strings.Split(outputStr, "\n")
	for _, line := range lines {
		if strings.Contains(line, "Label:") {
			// Extract label from line like "Label:            FabricToken-OrdererOrg1"
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				existingLabel := parts[len(parts)-1]
				if existingLabel == label {
					return true, nil
				}
			}
		}
	}

	return false, nil
}

// ListTokens returns a list of all available token labels
func (p *SoftHSMProvider) ListTokens() ([]string, error) {
	cmd := exec.Command(p.utilPath, "--show-slots")
	cmd.Env = append(os.Environ(), fmt.Sprintf("SOFTHSM2_CONF=%s", p.config.ConfigPath))

	output, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("failed to list tokens: %w", err)
	}

	// Parse output to extract token labels
	var tokens []string
	lines := strings.Split(string(output), "\n")
	for _, line := range lines {
		if strings.Contains(line, "Label:") {
			// Extract label from line like "Label:            FabricToken-OrdererOrg1"
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				label := parts[len(parts)-1]
				if label != "" {
					tokens = append(tokens, label)
				}
			}
		}
	}

	return tokens, nil
}

// GetLibraryPath returns the SoftHSM2 library path
func (p *SoftHSMProvider) GetLibraryPath() string {
	return p.libraryPath
}

// GetConfigPath returns the SoftHSM2 configuration file path
func (p *SoftHSMProvider) GetConfigPath() string {
	return p.config.ConfigPath
}

// GetEnvironment returns environment variables needed for SoftHSM2
func (p *SoftHSMProvider) GetEnvironment() map[string]string {
	return map[string]string{
		"SOFTHSM2_CONF": p.config.ConfigPath,
	}
}

// Validate verifies that SoftHSM2 is properly configured
func (p *SoftHSMProvider) Validate() error {
	// Check if softhsm2-util is available
	if p.utilPath == "" {
		return fmt.Errorf("softhsm2-util not found")
	}

	// Check if library exists
	if _, err := os.Stat(p.libraryPath); os.IsNotExist(err) {
		return fmt.Errorf("SoftHSM2 library not found at %s", p.libraryPath)
	}

	return nil
}

// findAvailableSlot finds an available slot for token creation
func (p *SoftHSMProvider) findAvailableSlot() (int, error) {
	cmd := exec.Command(p.utilPath, "--show-slots")
	cmd.Env = append(os.Environ(), fmt.Sprintf("SOFTHSM2_CONF=%s", p.config.ConfigPath))

	output, err := cmd.CombinedOutput()
	if err != nil {
		return 0, fmt.Errorf("failed to list slots: %w", err)
	}

	// Parse output to find uninitialized slot
	lines := strings.Split(string(output), "\n")
	var currentSlot int
	for _, line := range lines {
		if strings.Contains(line, "Slot ") {
			// Extract slot number
			var slot int
			if _, err := fmt.Sscanf(line, "Slot %d", &slot); err == nil {
				currentSlot = slot
			}
		} else if currentSlot > 0 && strings.Contains(line, "Initialized:") && strings.Contains(line, "no") {
			return currentSlot, nil
		}
	}

	// If no uninitialized slot found, use slot 0 (SoftHSM will auto-assign)
	return 0, nil
}

// findSoftHSMUtil finds the softhsm2-util binary
func findSoftHSMUtil() (string, error) {
	// Try PATH first
	if path, err := exec.LookPath("softhsm2-util"); err == nil {
		return path, nil
	}

	// Try common installation paths
	commonPaths := []string{
		"/opt/homebrew/opt/softhsm@2.5/bin/softhsm2-util",
		"/opt/homebrew/bin/softhsm2-util",
		"/usr/local/opt/softhsm/bin/softhsm2-util",
		"/usr/bin/softhsm2-util",
		"/usr/local/bin/softhsm2-util",
	}

	for _, path := range commonPaths {
		if _, err := os.Stat(path); err == nil {
			return path, nil
		}
	}

	return "", fmt.Errorf("softhsm2-util not found. Please install SoftHSM2:\n  macOS: brew install softhsm\n  Linux: apt-get install softhsm2")
}

// autoDetectSoftHSMLibrary auto-detects the SoftHSM2 library path
func autoDetectSoftHSMLibrary() string {
	switch runtime.GOOS {
	case "darwin":
		paths := []string{
			"/opt/homebrew/opt/softhsm@2.5/lib/softhsm/libsofthsm2.so",
			"/opt/homebrew/opt/softhsm/lib/softhsm/libsofthsm2.so",
			"/opt/homebrew/lib/softhsm/libsofthsm2.so",
			"/usr/local/opt/softhsm/lib/softhsm/libsofthsm2.so",
			"/usr/local/lib/softhsm/libsofthsm2.so",
		}
		for _, p := range paths {
			if _, err := os.Stat(p); err == nil {
				return p
			}
		}
		return "/opt/homebrew/opt/softhsm@2.5/lib/softhsm/libsofthsm2.so"
	case "linux":
		paths := []string{
			"/usr/lib64/softhsm/libsofthsm2.so",
			"/usr/lib/softhsm/libsofthsm2.so",
			"/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so",
		}
		for _, p := range paths {
			if _, err := os.Stat(p); err == nil {
				return p
			}
		}
		return "/usr/lib64/softhsm/libsofthsm2.so"
	default:
		return "/usr/lib/softhsm/libsofthsm2.so"
	}
}
